"""documents and document versions

Revision ID: 9c6f36c3bd9b
Revises: c3dca4c88300
Create Date: 2026-09-19 20:19:57.474716

Architecture §9. Two tables: ``documents`` is the stable identity a citation refers to,
``document_versions`` is one uploaded file, written once and never edited.

Three choices worth knowing before altering either table:

* **``documents.current_version`` is a number, not a foreign key.** A key to
  ``document_versions.id`` plus the one already pointing back at ``documents`` is a
  circular FK — use_alter, a post_update relationship and a two-step migration — and
  the unique constraint on ``(document_id, version_number)`` already makes the number
  resolve to exactly one row.
* **``(organization_id, content_hash)`` is an index, not a unique constraint.**
  Deduplication is scoped per organization in the service (Task 6), but a document
  whose version 3 restores version 1"s content is legitimate and would violate
  uniqueness here.
* **``document_versions.organization_id`` is denormalised from the parent document.**
  Invariant 1 requires every tenant-scoped row to carry its own tenant, so the scoped
  repository can filter this table without a join — a filter that depends on a join is
  a filter someone can drop.

``created_by`` and ``uploaded_by`` are ON DELETE SET NULL: deleting the person who
uploaded the employee handbook must not delete the handbook.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c6f36c3bd9b"
down_revision: str | Sequence[str] | None = "c3dca4c88300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("current_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "ready",
                "failed",
                name="document_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_created_by"), "documents", ["created_by"], unique=False)
    op.create_index(
        "ix_documents_org_created_at", "documents", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_versions_doc_number"
        ),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_index(
        "ix_document_versions_org_hash",
        "document_versions",
        ["organization_id", "content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_organization_id"),
        "document_versions",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_versions_organization_id"), table_name="document_versions")
    op.drop_index("ix_document_versions_org_hash", table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_index("ix_documents_org_created_at", table_name="documents")
    op.drop_index(op.f("ix_documents_created_by"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
