"""audit log for cross-tenant reads and membership changes

Revision ID: c3dca4c88300
Revises: d569445357ca
Create Date: 2026-09-19 16:10:37.702848

Architecture §7.10 requires that every cross-tenant read by a platform operator is
recorded with who, which organization, which resource, when, and the stated reason.
The membership service writes ordinary lifecycle rows here too, so "who removed this
person?" has an answer that does not depend on log retention.

Two deliberate omissions:

* **No foreign key on ``organization_id``.** An organization can be deleted, and the
  audit row describing its deletion has to outlive it.
* **No ``updated_at``.** The rows are append-only by convention, and a column implying
  an audit record can be edited is the wrong column to put on an audit record.

``actor_user_id`` is ON DELETE SET NULL rather than CASCADE: deleting an operator"s
account must not erase what they did.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3dca4c88300"
down_revision: str | Sequence[str] | None = "d569445357ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "via_super_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_log_actor_created",
        "audit_log",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    # Partial: answers "did anyone read across tenants?" without scanning the table.
    op.create_index(
        "ix_audit_log_cross_tenant",
        "audit_log",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("via_super_admin"),
    )
    op.create_index(
        "ix_audit_log_org_created",
        "audit_log",
        ["organization_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_org_created", table_name="audit_log")
    op.drop_index(
        "ix_audit_log_cross_tenant",
        table_name="audit_log",
        postgresql_where=sa.text("via_super_admin"),
    )
    op.drop_index("ix_audit_log_actor_created", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
